[package]
name = "moonshine-tray"
version.workspace = true
edition = "2024"

[[bin]]
name = "moonshine-tray"
path = "src/main.rs"

[dependencies]
bytes = "1.11.1"
clap = { version = "4.6.1", features = ["derive"] }
http-body-util = "0.1.3"
hyper = { version = "1.10.1", features = ["client", "http1"] }
hyper-util = { version = "0.1.20", features = ["tokio"] }
ksni = "0.3.6"
open = "5.3.5"
tokio = { version = "1.52.3", features = ["macros", "net", "process", "rt-multi-thread", "signal", "sync", "time"] }
toml = "1.1.2"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
zbus = "5.18.0"
